### ISSUE TITLE
exception when opening a repository with files that aren't present

### ISSUE THREAD

**Issue by db48x** [alpernebbi/git-annex-metadata-gui#3]
Traceback (most recent call last):
  File "/usr/local/bin/git-annex-metadata-gui", line 9, in <module>
    load_entry_point('git-annex-metadata-gui==0.1.0', 'gui_scripts', 'git-annex-metadata-gui')()
  File "/usr/local/lib/python3.5/dist-packages/git_annex_metadata_gui-0.1.0-py3.5.egg/git_annex_metadata_gui/gui.py", line 43, in main
  File "/usr/local/lib/python3.5/dist-packages/git_annex_metadata_gui-0.1.0-py3.5.egg/git_annex_metadata_gui/gui.py", line 158, in load_repository
  File "/usr/local/lib/python3.5/dist-packages/git_annex_metadata_gui-0.1.0-py3.5.egg/git_annex_metadata_gui/models.py", line 97, in __init__
  File "/usr/local/lib/python3.5/dist-packages/git_annex_metadata_gui-0.1.0-py3.5.egg/git_annex_metadata_gui/models.py", line 161, in __getitem__
  File "/usr/local/lib/python3.5/dist-packages/git_annex_metadata_gui-0.1.0-py3.5.egg/git_annex_metadata_gui/models.py", line 172, in __getitem__
KeyError: 'SHA256E-s817469--25cce8a7f4b452954eb6f6438069b0a8c1f953eb41306710b3d78b5bc6ff4ff8.oga'

**Comment by alpernebbi** [comment]
Ok, I can reproduce this by deleting the `aaa/bbb/*.log` from the `git-annex` branch of a new repository, by doing:
```
git init
git-annex init
touch a.txt
git-annex add a.txt
git commit -m "add a.txt"
git checkout git-annex
git rm 1ce/df4/*.log
git commit -m "del log"
git checkout master
```
At this point `git-annex metadata --all --json` gives me nothing, but `git-annex metadata --json` gives me the expected output. 
```
$ git-annex metadata --json
{"command":"metadata","note":"","success":true,"key":"SHA256E-s0--e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.txt","file":"a.txt","fields":{}}
$ git-annex metadata --json --all
# No output
```
In my program, I'm using the outputs of these two commands to get the files and the keys associated with the annex and checking these. It finds your file in the files, tries to wrap an object created from its key, but it cannot find the key in all known keys, so raises an error.

Running `git-annex fsck` fixed the deleted log and the crash for me, please try that.
```
$ git-annex fsck
fsck a.txt (fixing location log) (checksum...) ok
(recording state in git...)
```

**Comment by db48x** [comment]
Hmm. I had thought that the file was simply not present, but it doesn't happen when testing that scenario specifically. A fsck does work, so that must be it. I suppose a reasonable fix would be to catch this sort of exception and recommend running fsck, rather than bailing.

**Comment by alpernebbi** [comment]
I don't think the problem with the log is supposed to happen. If you find a way to reproduce it, you might want to [report it to git-annex](https://git-annex.branchable.com/bugs/).

For now, I updated the `git-annex-adapter` code so that it can create a metadata object for any valid key (checked via `examinekey`). Now it works as usual even in this case.

**Comment by db48x** [comment]
That's an even better fix; thanks!

Now if I could just figure out how to reproduce the git-annex problem...
