### ISSUE TITLE
Crashes after clicking on annex'ed file without content

### ISSUE THREAD

**Issue by yarikoptic** [alpernebbi/git-annex-metadata-gui#6]
```shell
hopa:~/datalad/labs/haxby/raiders
$> git-annex-metadata-gui .
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/3rd/git-annex-metadata-gui/git_annex_metadata_gui/gui.py", line 222, in selection_updated
    self.docks.preview.set_item(item)
  File "/home/yoh/proj/datalad/3rd/git-annex-metadata-gui/git_annex_metadata_gui/docks.py", line 65, in set_item
    if mime.startswith('text/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
[1]    7003 abort      git-annex-metadata-gui .
```

I guess getting some at least smoke tests (not yet sure how easy/difficult but should be possible with all the GUI nature) could benefit I guess the "stability" ;)

**Comment by alpernebbi** [comment]
Well, I had been sneaky again and fixed it yesterday (54eb659), so closing this.
